const mem = new Map()
globalThis.window = { localStorage: { getItem: k => mem.get(k) ?? null, setItem: (k, v) => mem.set(k, v), removeItem: k => mem.delete(k) }, dispatchEvent: () => true, setTimeout }
globalThis.CustomEvent = class { constructor(t, o) { this.type = t; this.detail = o?.detail } }
let pass = 0, fail = 0
const ok = (n, c, x = '') => { if (c) { pass++; console.log('  ✓', n) } else { fail++; console.log('  ✗ FAIL:', n, x) } }

const { useAuthStore, MAX_ATTEMPTS } = await import('@/store/auth.store')
const { passwordProblem } = await import('@/lib/password')
const A = () => useAuthStore.getState()

console.log('\nPassword rules')
ok('too short', !!passwordProblem('abc123', 'a@b.com'))
ok('digits only', !!passwordProblem('12345678901', 'a@b.com'))
ok('common password', !!passwordProblem('Password123', 'a@b.com'))
ok('contains email name', !!passwordProblem('chidinma-rocks1', 'chidinma@mail.com'))
ok('good password accepted', passwordProblem('Tr1cky-Walnut-Table', 'a@b.com') === null)

console.log('\nRegistration')
ok('bad email rejected', (await A().register({ name: 'A', email: 'nope', phone: '1', password: 'Tr1cky-Walnut-Table' })).ok === false)
ok('weak password rejected', (await A().register({ name: 'A', email: 'a@b.com', phone: '1', password: 'short' })).ok === false)
const r = await A().register({ name: 'Ade Bello', email: 'Ade@Shop.NG', phone: '0803', password: 'Tr1cky-Walnut-Table', role: 'vendor', businessName: 'Ade Woodworks' })
ok('vendor registers', r.ok && A().user.role === 'vendor' && A().user.businessName === 'Ade Woodworks')
ok('email normalised', A().user.email === 'ade@shop.ng')
const stored = Object.values(A().accounts)[0]
ok('password is NOT stored in plain text', !JSON.stringify(A()).includes('Tr1cky-Walnut-Table') && stored.hash.length === 64)
ok('duplicate email rejected', (await A().register({ name: 'X', email: 'ade@shop.ng', phone: '1', password: 'Another-Good-Pass9' })).ok === false)

console.log('\nPrivilege escalation')
const adminTry = await A().register({ name: 'Eve', email: 'eve@evil.com', phone: '1', password: 'Tr1cky-Walnut-Table', role: 'admin' })
ok('cannot self-register as admin', adminTry.ok && A().user.role === 'customer', A().user?.role)
const logiTry = await A().register({ name: 'Eve2', email: 'eve2@evil.com', phone: '1', password: 'Tr1cky-Walnut-Table', role: 'logistics' })
ok('cannot self-register as logistics', logiTry.ok && A().user.role === 'customer')
ok('cannot self-register as super_admin', (await A().register({ name: 'E3', email: 'e3@evil.com', phone: '1', password: 'Tr1cky-Walnut-Table', role: 'super_admin' })).ok && A().user.role === 'customer')

console.log('\nLogin')
A().logout()
ok('logged out', A().user === null && !A().isAuthenticated)
const bad = await A().login('ade@shop.ng', 'wrong-password-1')
ok('wrong password rejected', !bad.ok && A().user === null)
const unknown = await A().login('ghost@nowhere.com', 'whatever-123')
ok('unknown email gives the SAME message', !unknown.ok && unknown.error === bad.error, `${unknown.error} vs ${bad.error}`)
const good = await A().login('  ADE@shop.ng ', 'Tr1cky-Walnut-Table')
ok('correct password signs in (email case/space-insensitive)', good.ok && A().user.email === 'ade@shop.ng')

console.log('\nLockout')
A().logout()
let last
for (let i = 0; i < MAX_ATTEMPTS; i++) last = await A().login('ade@shop.ng', 'nope-nope-' + i)
ok(`locked after ${MAX_ATTEMPTS} failures`, !last.ok && /Too many/.test(last.error), last.error)
const whileLocked = await A().login('ade@shop.ng', 'Tr1cky-Walnut-Table')
ok('even the CORRECT password is refused while locked', !whileLocked.ok && /Too many/.test(whileLocked.error))
ok('lock is per-email (others unaffected)', (await A().login('eve@evil.com', 'Tr1cky-Walnut-Table')).ok)
A().logout()
useAuthStore.setState(s => ({ attempts: { ...s.attempts, 'ade@shop.ng': { count: 0, lockedUntil: Date.now() - 1000 } } }))
ok('lock expires', (await A().login('ade@shop.ng', 'Tr1cky-Walnut-Table')).ok)
ok('successful login clears the failure counter', !A().attempts['ade@shop.ng'])

console.log('\nDev shortcut')
ok('devLogin refuses outside DEV builds', A().devLogin('admin@karta.test', 'admin') === false && A().user.role !== 'admin')


console.log('\nDriver accounts (staff-created)')
const asUser = (u) => useAuthStore.setState({ user: u, isAuthenticated: !!u })
const driverData = { name: 'Musa Ibrahim', email: 'Musa@Karta.test', phone: '0803 555 1234' }

asUser(null)
ok('signed-out cannot create drivers', (await A().createLogisticsAccount(driverData)).ok === false)
asUser({ id: 'c', name: 'Cust', email: 'cust@x.com', role: 'customer' })
ok('customer cannot create drivers', (await A().createLogisticsAccount(driverData)).ok === false)
asUser({ id: 'v', name: 'Vend', email: 'vend@x.com', role: 'vendor' })
ok('vendor cannot create drivers', (await A().createLogisticsAccount(driverData)).ok === false)

asUser({ id: 'a', name: 'Admin', email: 'admin@karta.test', role: 'admin' })
ok('invalid phone rejected', (await A().createLogisticsAccount({ ...driverData, phone: '123' })).ok === false)
ok('invalid email rejected', (await A().createLogisticsAccount({ ...driverData, email: 'nope' })).ok === false)
const made = await A().createLogisticsAccount(driverData)
ok('admin creates a driver', made.ok)
ok('temp password is readable and strong enough to pass the rules', /^[A-Za-z2-9]{4}-[A-Za-z2-9]{4}-[A-Za-z2-9]{4}$/.test(made.tempPassword) && passwordProblem(made.tempPassword, 'musa@karta.test') === null, made.tempPassword)
ok('temp password is NOT stored in plain text', !JSON.stringify(A()).includes(made.tempPassword))
ok('role is logistics, flagged for password change', A().accounts['musa@karta.test'].user.role === 'logistics' && A().accounts['musa@karta.test'].user.mustChangePassword === true)
ok('records who created it', A().accounts['musa@karta.test'].createdBy === 'admin@karta.test')
ok('duplicate driver email rejected', (await A().createLogisticsAccount(driverData)).ok === false)
const second = await A().createLogisticsAccount({ ...driverData, email: 'second@karta.test' })
ok('each driver gets a different password', second.ok && second.tempPassword !== made.tempPassword)

A().logout()
ok('driver signs in with the temp password', (await A().login('musa@karta.test', made.tempPassword)).ok && A().user.role === 'logistics')
ok('…and is told to change it', A().user.mustChangePassword === true)
ok('wrong current password rejected', (await A().changePassword('not-the-password', 'Brand-New-Pass7')).ok === false)
ok('same password rejected', (await A().changePassword(made.tempPassword, made.tempPassword)).ok === false)
ok('weak new password rejected', (await A().changePassword(made.tempPassword, 'short')).ok === false)
ok('driver changes password', (await A().changePassword(made.tempPassword, 'Brand-New-Pass7')).ok)
ok('flag cleared after change', A().user.mustChangePassword === false && A().accounts['musa@karta.test'].user.mustChangePassword === false)
A().logout()
ok('old temp password no longer works', (await A().login('musa@karta.test', made.tempPassword)).ok === false)
ok('new password works', (await A().login('musa@karta.test', 'Brand-New-Pass7')).ok)

asUser({ id: 'd', name: 'Driver', email: 'musa@karta.test', role: 'logistics' })
ok('driver cannot deactivate others', A().setAccountDisabled('second@karta.test', true).ok === false)
asUser({ id: 'a', name: 'Admin', email: 'admin@karta.test', role: 'admin' })
ok('admin deactivates a driver', A().setAccountDisabled('musa@karta.test', true).ok)
ok('admin cannot deactivate themselves', (A().accounts['admin@karta.test'] || true) && A().setAccountDisabled('admin@karta.test', true).ok === false)
ok('only driver accounts can be toggled (not customers)', A().setAccountDisabled('ade@shop.ng', true).ok === false)
A().logout()
const dis = await A().login('musa@karta.test', 'Brand-New-Pass7')
ok('deactivated driver cannot sign in, even with the right password', !dis.ok && /deactivated/.test(dis.error), dis.error)
const wrongDis = await A().login('musa@karta.test', 'wrong-password-1')
ok('wrong password on a deactivated account does not reveal its status', !wrongDis.ok && !/deactivated/.test(wrongDis.error))
asUser({ id: 'a', name: 'Admin', email: 'admin@karta.test', role: 'admin' })
ok('admin reactivates', A().setAccountDisabled('musa@karta.test', false).ok)
A().logout()
ok('reactivated driver can sign in again', (await A().login('musa@karta.test', 'Brand-New-Pass7')).ok)

console.log(`\n${pass} passed, ${fail} failed`)
process.exit(fail ? 1 : 0)
